name: Release
on:
  push:
    tags:
      - 'release_*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - run: mvn --batch-mode --update-snapshots package
      - run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\/release_/}" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        id: upload-release-zip 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./target/jmxeval.zip
          asset_name: jmxeval-${{ env.RELEASE_VERSION }}-bin.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        id: upload-release-tar 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./target/jmxeval.tar.gz
          asset_name: jmxeval-${{ env.RELEASE_VERSION }}-bin.tar.gz
          asset_content_type: application/gzip